input {
  beats {
    port => 5044
  }
}

filter {
  mutate { add_field => { "[event][dataset]" => "finova.beats" } }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "finova-metrics-%{+YYYY.MM.dd}"
  }
}