apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  namespace: finova
  labels:
    app.kubernetes.io/name: fraud-service
    app.kubernetes.io/part-of: finova
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fraud-service
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
